specVersion: 0.0.1
description: "A subquery project for finding moonbeam contributors who haven't set their rewards address"
repository: git@github.com:talismansociety/moonbeam-contributors.git
schema: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 7538550 # before the moonbeam crowdloan went live
    # startBlock: 7600000 # before the first talisman moonbeam crowdloan contribution
    mapping:
      handlers:
        - handler: handleContributed
          kind: substrate/EventHandler
          filter:
            module: crowdloan
            method: Contributed
        - handler: handleMemoUpdated
          kind: substrate/EventHandler
          filter:
            module: crowdloan
            method: MemoUpdated
